compute_environment: LOCAL_MACHINE
debug: false
# distributed_type: MULTI_GPU
distributed_type: no
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
gpu_ids: "6,7"
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false